# Generated by Django 5.2.7 on 2025-12-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_profile_name_remove_profile_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_year', models.CharField(blank=True, max_length=10, null=True)),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('program', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
