# Generated by Django 5.2.7 on 2026-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='is_verified',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='trx_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
