# Generated by Django 5.2.13 on 2026-04-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_membermemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermemory',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
