# Generated by Django 5.2.13 on 2026-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_membermemory_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=20)),
                ('description', models.TextField()),
                ('animation_url', models.URLField(help_text='Link to exercise GIF or Lottie animation')),
                ('calories_per_rep', models.FloatField(default=0.5)),
            ],
        ),
    ]
