# Generated by Django 5.2.13 on 2026-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='animation_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='calories_per_rep',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Core', 'Core'), ('Full Body', 'Full Body')], default='Full Body', max_length=50),
        ),
    ]
