# Generated by Django 5.2.13 on 2026-04-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_remove_exercise_animation_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='animation_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='calories_per_rep',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Temporary Exercise', max_length=100),
            preserve_default=False,
        ),
    ]
