# Generated by Django 5.2.13 on 2026-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_weight',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
    ]
