# Generated by Django 5.2.13 on 2026-04-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_profile_goal_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='breakfast',
            field=models.TextField(default='Healthy Breakfast'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dinner',
            field=models.TextField(default='Healthy Dinner'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='lunch',
            field=models.TextField(default='Healthy Lunch'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(max_length=500)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='frontend.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
