# Generated by Django 5.2.13 on 2026-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_dailychallenge_challengesubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gym_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
