# Generated by Django 5.2.13 on 2026-04-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_profile_gym_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='coins_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='coins_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
