# Generated by Django 5.2.13 on 2026-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_per_minute',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='animation_url',
            field=models.URLField(blank=True, help_text='Link to exercise GIF or animation', max_length=500, null=True),
        ),
    ]
