# Generated by Django 5.2.13 on 2026-04-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_alter_payment_options_remove_payment_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
