# Generated by Django 5.2.13 on 2026-04-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_dietplan_user_field'),
        ('frontend', '0032_delete_membership'),
    ]

    operations = [
    ]
