# Generated by Django 5.2.13 on 2026-04-29 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_merge_0021_dietplan_user_field_0032_delete_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=170.0),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
